server:
  port: 8011

spring:
  application:
    name: util
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      key-prefix: "HIKI_WX:"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    hostname: util

OSS:
  endpoint: ""
  accessKeyId: ""
  accessKeySecret: ""
  bucketName: ""

